// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sodalis.Modules.Identity.Persistence;

#nullable disable

namespace Sodalis.Modules.Identity.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sodalis.Modules.Identity.Domain.ExternalIdentity", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.HasKey("PlayerId", "ProviderId")
                        .HasName("pk_external_identities");

                    b.HasIndex("GameId", "ProviderId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_external_identities_game_id_provider_id_external_id");

                    b.ToTable("external_identities", "identity");
                });

            modelBuilder.Entity("Sodalis.Modules.Identity.Domain.Player", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.HasKey("PlayerId")
                        .HasName("pk_players");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_players_game_id");

                    b.ToTable("players", "identity");
                });

            modelBuilder.Entity("Sodalis.Modules.Identity.Domain.ExternalIdentity", b =>
                {
                    b.HasOne("Sodalis.Modules.Identity.Domain.Player", null)
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_players_player_id");
                });

            modelBuilder.Entity("Sodalis.Modules.Identity.Domain.Player", b =>
                {
                    b.Navigation("ExternalIdentities");
                });
#pragma warning restore 612, 618
        }
    }
}
